import 'package:herogame/app.dart';
import 'package:flutter/widgets.dart';

abstract class RouterService {
  /// Instance of the app this router belongs too
  /// It can/will be provided to routes generated by this router
  App app;

  /// Static routes. These generally don't require input parameters
  Map<String, WidgetBuilder> routes;

  /// Dynamic routes that expect arguments passed to them
  Map<String, Function> routeBuilders;

  Route<dynamic> onGenerateRoute(RouteSettings settings);
}
