import 'package:herogame/app.dart';
import 'package:herogame/services/router.dart';
import 'package:herogame/views/battle_screen.dart';
import 'package:herogame/views/character_selection.dart';

import 'package:herogame/views/home_screen.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class Routes {
  static const home = "/";
  static const loginScreen = "/login";

  static const splash = "/splash";
  static const character = "/character";
  static const battle = "/battle";
}

class AppRouter implements RouterService {
  AppRouter(this.app) {
    routes = {
      Routes.home: (_) => HomeScreen(app: app),
      Routes.character: (_) => CharacterSelector(app: app),
      Routes.battle: (_) => BattleScreen(app: app),
    };

    routeBuilders = {};
  }

  /// Instance of the app this router belongs too
  /// It can/will be provided to routes generated by this router
  @override
  App app;

  /// Static routes. These generally don't require input parameters
  @override
  Map<String, WidgetBuilder> routes;

  /// Dynamic routes that expect arguments passed to them
  @override
  Map<String, Function> routeBuilders;

  @override
  Route<dynamic> onGenerateRoute(RouteSettings settings) {
    if (routeBuilders.containsKey(settings.name)) {
      return routeBuilders[settings.name](settings.arguments);
    }

    return MaterialPageRoute(
      builder: (context) => HomeScreen(),
    );
  }
}

class SpashScreenArguments extends Object {
  final String message;
  SpashScreenArguments({this.message});
}

// *************************************************************************
// Arguments holder classes
// **************************************************************************
